###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = export KITTY_OPACITY=$(~/.config/hypr/scripts/vars.sh get transparency); if [ "$KITTY_OPACITY" == "true" ]; then kitty -o background_opacity=0.8; else kitty; fi
$fileManager = dolphin
$menu = hyprlauncher

$initTheme = ~/.config/hypr/scripts/init-theme.sh
$themePicker = ~/.config/hypr/scripts/theme-picker.sh
