$image = {wallpaper}

$background = rgba({background.strip}ff)
$surface = rgba({background.strip}ff)
$surface_dim = rgba({background.strip}ff)
$surface_bright = rgba({color8.strip}ff)
$surface_container_lowest = rgba({background.strip}ff)
$surface_container_low = rgba({color0.strip}ff)
$surface_container = rgba({color0.strip}ff)
$surface_container_high = rgba({color8.strip}ff)
$surface_container_highest = rgba({color8.strip}ff)

$primary = rgba({color1.strip}ff)
$primary_fixed = rgba({color9.strip}ff)
$primary_fixed_dim = rgba({color1.strip}ff)
$primary_container = rgba({color9.strip}ff)
$surface_tint = rgba({color1.strip}ff)

$secondary = rgba({color2.strip}ff)
$secondary_fixed = rgba({color10.strip}ff)
$secondary_fixed_dim = rgba({color2.strip}ff)
$secondary_container = rgba({color10.strip}ff)

$tertiary = rgba({color3.strip}ff)
$tertiary_fixed = rgba({color11.strip}ff)
$tertiary_fixed_dim = rgba({color3.strip}ff)
$tertiary_container = rgba({color11.strip}ff)

$on_background = rgba({foreground.strip}ff)
$on_surface = rgba({foreground.strip}ff)
$on_surface_variant = rgba({color7.strip}ff)
$on_primary = rgba({background.strip}ff)
$on_primary_container = rgba({foreground.strip}ff)
$on_secondary = rgba({background.strip}ff)
$on_secondary_container = rgba({foreground.strip}ff)
$on_tertiary = rgba({background.strip}ff)
$on_tertiary_container = rgba({foreground.strip}ff)

$error = rgba({color1.strip}ff)
$error_container = rgba({color9.strip}ff)
$outline = rgba({color4.strip}ff)
$outline_variant = rgba({color8.strip}ff)
$source_color = rgba({color1.strip}ff)
$shadow = rgba(000000ff)
$scrim = rgba(000000ff)

$surface_variant = rgba({color9.strip}ff)
