# RetroLinux Plymouth Theme Script

Window.SetBackgroundTopColor(0.0, 0.0, 0.0);
Window.SetBackgroundBottomColor(0.0, 0.0, 0.0);

logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2);
logo.sprite.SetOpacity(1);

fun quit_callback()
  {
    logo.sprite.SetOpacity(1);
  }

Plymouth.SetQuitFunction(quit_callback);

message_sprite = Sprite();
message_sprite.SetPosition(10, 10, 10000);

fun display_message_callback(text)
  {
    my_image = Image.Text(text, 1, 1, 1);
    message_sprite.SetImage(my_image);
  }

fun hide_message_callback(text)
  {
    message_sprite.SetOpacity(0);
  }

Plymouth.SetDisplayMessageFunction(display_message_callback);
Plymouth.SetHideMessageFunction(hide_message_callback);
