[config]
mode = "dark"
contrast = 0.2
lightness_dark = -0.1
source_color_index = 0

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.cache/retro/themes/hyprland-colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.cache/retro/themes/kitty-colors.conf'
post_hook = 'bash ~/.config/kitty/scripts/refresh_kitty.sh'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim.json'
output_path = '~/.cache/retro/themes/nvim-colors.json'
