[config]
contrast = 1.0
base16_backend = "wal"
source_color_index = 0
type = "scheme-vibrant"

[templates.hyprland]
pre_hook = 'bash ~/.config/hypr/scripts/refresh_hyprland.sh'
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/retro/themes/hyprland-colors.conf'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/retro/themes/kitty-colors.conf'
post_hook = 'bash ~/.config/kitty/scripts/refresh_kitty.sh'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim.json'
output_path = '~/.config/retro/themes/nvim-colors.json'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasm'
output_path = '~/.config/retro/themes/rofi-colors.rasi'
post_hook = 'bash ~/.config/rofi/scripts/refresh_rofi.sh'

[templates.colors-css]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/retro/themes/colors.css'
