[config]
contrast = 0
base16_backend = "wal"
source_color_index = 0
type = "scheme-vibrant"

[templates.hyprland]
pre_hook = 'bash ~/.config/hypr/scripts/refresh_hyprland.sh'
input_path = '~/.config/matugen/templates/hyprland.lua'
output_path = '~/.config/retro/themes/hyprland-colors.lua'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/retro/themes/kitty-colors.conf'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasm'
output_path = '~/.config/retro/themes/rofi-colors.rasi'

[templates.colors-css]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/retro/themes/colors.css'

[templates.gtk2]
pre_hook = 'mkdir -p ~/.config/gtk-2.0'
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-2.0/gtk.css'

[templates.gtk3]
pre_hook = 'mkdir -p ~/.config/gtk-3.0'
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
pre_hook = 'mkdir -p ~/.config/gtk-4.0'
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kvantum_kvconfig]
pre_hook = 'mkdir -p ~/.config/Kvantum/matugen'
input_path = '~/.config/matugen/templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
pre_hook = 'mkdir -p ~/.config/Kvantum/matugen'
input_path = '~/.config/matugen/templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.firefox-website-colors]
input_path = "~/.config/matugen/templates/firefox.css"
output_path = "~/.config/retro/themes/firefox.css"

[templates.cava]
pre_hook = 'mkdir -p ~/.config/cava/themes'
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/retro'
post_hook = 'pkill -USR1 cava 2>/dev/null || true'
