#!/bin/bash

# TODO: Make a script that also generates custom windowrules
# and make a variable like RETRO_OPACITY_SKIP awhich will be
# a arrway of apps that will not be affected by the opacity
# or even better i think I should make a variable array
# of apps that should have opacity

OUTPUT="$HOME/.cache/retro/themes/variables.conf"
TEMP_FILE=$(mktemp)

mkdir -p "$(dirname "$OUTPUT")"

get_val() {
    local val=$(retro variable get "$1" 2>/dev/null)
    echo "${val:-$2}"
}

BORDER=$(get_val "RETRO_BORDER_SIZE" "2")
ROUNDING=$(get_val "RETRO_ROUNDING" "10")
SHADOW=$(get_val "RETRO_SHADOW" "true")
BLUR=$(get_val "RETRO_BLUR" "true")
GAP_IN=$(get_val "RETRO_GAP_IN" "5")
GAP_OUT=$(get_val "RETRO_GAP_OUT" "20")
TRANS=$(get_val "RETRO_OPACITY" "1.0")
INACTIVE_TRANS=$(get_val "RETRO_INACTIVE_OPACITY" "0.8")

cat <<EOF >"$TEMP_FILE"
##########################################
###   RETRO AUTO-GENERATED VARIABLES   ###
##########################################

# This file has been generated by Retro. Do not edit manually.

\$retro_opacity = $TRANS
\$retro_inactive_opacity = $INACTIVE_TRANS
\$retro_border_size = $BORDER
\$retro_rounding = $ROUNDING
\$retro_gap_in = $GAP_IN
\$retro_gap_out = $GAP_OUT
\$retro_shadow = $SHADOW
\$retro_blur = $BLUR
EOF

if mv "$TEMP_FILE" "$OUTPUT"; then
    chmod 644 "$OUTPUT"

    hyprctl reload 2>/dev/null
else
    rm -f "$TEMP_FILE"
    exit 1
fi
