cursor            #f8adfc
cursor_text_color #51145a

foreground        #e2e2e2
background        #131313

selection_foreground #3b2b3c
selection_background #d8bfd5
url_color         #f8adfc

#: black
color0  #100914
color8  #361d3c

#: red 
color1  #5c3063
color9  #49264f

#: green 
color2  #954d9e
color10 #954d9e

#: yellow 
color3  #82448b
color11 #5c3063

#: blue 
color4  #f8adfc
color12 #ffd6fd

#: magenta
color5  #bf49d0
color13 #82448b

#: cyan 
color6  #954d9e
color14 #59295f

#: white 
color7  #c6c6c6
color15 #6f3a77

# --- Tab Bar & Borders ---
active_tab_foreground   #51145a
active_tab_background   #f8adfc
active_border_color     #f8adfc
inactive_border_color   #919191
