.pragma library

var data = {
    "position": "top",
    "launcherIcon": "",
    "launcherIconTint": true,
    "launcherIconFullTint": true,
    "launcherIconSize": 24,
    "pillStyle": "default",
    "screenList": [],
    "enableFirefoxPlayer": false,
    "barColor": [["surface", 0.0]],
    "frameEnabled": false,
    "frameThickness": 6,
    "pinnedOnStartup": true,
    "hoverToReveal": true,
    "hoverRegionHeight": 8,
    "showPinButton": true,
    "availableOnFullscreen": false,
    "use12hFormat": false,
    "containBar": false,
    "keepBarShadow": false,
    "keepBarBorder": false,
    "scale": 1.0,
    "barPaddingTop": 4,
    "barPaddingRight": 4,
    "barPaddingBottom": 4,
    "barPaddingLeft": 4,
    "showWeatherTemp": false,
    "showDayOfWeek": false,
    "batteryStyle": "arch",
    "toolboxOrder": ["screenshot", "screenshots", "separator", "recorder", "recordings", "separator", "colorpicker", "ocr", "qr", "lens", "shazam", "webcam", "docker"],
    "clockOrder": ["clock", "weather", "pomodoro"],
    "barLeftOrder": ["launcher", "workspaces", "pin"],
    "barRightOrder": ["tools", "tray", "wifi", "bluetooth", "controls", "battery", "clock", "power"]
}
