#
# /etc/pacman.conf - Offline build configuration
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
NoProgressBar
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional

[offline]
SigLevel = Optional TrustAll
Server = file:///var/cache/retrolinux/mirror/offline/