###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$loadRetro = retro --load

# Set programs that you use
$terminal = retro -app kitty open;
$fileManager = dolphin;
$menu = hyprlauncher;
