-- This file has been generated by Retro Settings

-- Intel GPU
hl.env("LIBVA_DRIVER_NAME", "iHD")
hl.env("VDPAU_DRIVER", "va_gl")
hl.env("mesa_glthread", "true")

hl.env("XCURSOR_THEME", "Moga-Black")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Moga-Black")
hl.env("PIPEWIRE_LATENCY", "1024/48000")
