-- Generated by Retro Settings

-- Settings
hl.config()

-- Window rules
hl.window_rule({
	name = "zen-opacity",
	match = {
		class = "zen",
	},
	opacity = "1.0 override 0.9 override",
})

hl.window_rule({
	match = {
		class = "^(org\\.gnome\\.Loupe)$",
	},
	float = true,
	size = "750 450",
})

hl.window_rule({
	name = "xwayland-video-bridge-fixes",
	match = {
		class = "xwaylandvideobridge",
	},
	max_size = "1 1",
	no_anim = true,
	no_blur = true,
	no_follow_mouse = true,
	no_initial_focus = true,
	opacity = "0.00 override 0.00 override",
})
