-- This file has been generated by Retro. Do not edit manually.
-- Use retro window add / retro window remove to manage rules

hl.window_rule({
    name = "zen-opacity",
    match = {
        class = "zen",
    },
    opacity = "1.0 override 0.9 override",
    
})

