#!/bin/bash

source "$RETRO_DIR/lib/helpers.sh"

RULES_FILE="$RETRO_CACHE/themes/windowrules.conf"

mkdir -p "$(dirname "$RULES_FILE")"

init_rules_file() {
    if [[ ! -f $RULES_FILE ]]; then
        cat >"$RULES_FILE" <<'EOF'
######################################
###   RETRO AUTO-GENERATED Rules   ###
######################################

# This file has been generated by Retro. Do not edit manually.
# Use retro window add / retro window remove to manage rules

EOF
    fi
}

_is_blacklisted() {
    local class="$1"
    local blacklist=$(get_var "RETRO_WINDOW_BLACKLIST")

    [[ -z $blacklist || $blacklist == "null" ]] && return 1

    IFS='|' read -ra BLACKLIST <<<"$blacklist"
    for item in "${BLACKLIST[@]}"; do
        [[ ${class,,} == "${item,,}" ]] && return 0
    done

    return 1
}

_list_rules() {
    init_rules_file

    local content=$(grep -v '^#' "$RULES_FILE" | grep -v '^[[:space:]]*$')
    if [[ -z $content ]]; then
        echo "NONE"
        return 0
    fi

    local in_windowrule=false
    local in_layerrule=false
    local current_rule=""
    local rule_type=""
    local anon_counter=0

    while IFS= read -r line || [[ -n $line ]]; do
        if [[ $line =~ ^windowrule[[:space:]] ]]; then
            if [[ $line =~ ^windowrule[[:space:]]*= ]]; then
                ((anon_counter++))
                echo "window|anon-${anon_counter}"
                in_windowrule=false
            else
                in_windowrule=true
                in_layerrule=false
                current_rule="$line"$'\n'
                rule_type="window"
            fi
        elif [[ $line =~ ^layerrule[[:space:]] ]]; then
            if [[ $line =~ ^layerrule[[:space:]]*= ]]; then
                ((anon_counter++))
                echo "layer|anon-${anon_counter}"
                in_layerrule=false
            else
                in_layerrule=true
                in_windowrule=false
                current_rule="$line"$'\n'
                rule_type="layer"
            fi
        elif [[ $line =~ ^[[:space:]]*\}[[:space:]]*$ ]] && ($in_windowrule || $in_layerrule); then
            current_rule+="$line"$'\n'
            if [[ -n $current_rule ]]; then
                local name=$(echo "$current_rule" | grep "^[[:space:]]*name =" | head -1 | sed 's/.*name = //' | tr -d ' ')
                if [[ -n $name ]]; then
                    echo "${rule_type}|${name}"
                fi
            fi
            in_windowrule=false
            in_layerrule=false
            current_rule=""
        elif ($in_windowrule || $in_layerrule); then
            current_rule+="$line"$'\n'
        fi
    done <"$RULES_FILE"
}

_add_windowrule() {
    local name="$1"
    local rule_content="$2"

    init_rules_file

    local class_match=$(echo "$rule_content" | grep -oP "match:class\s*=\s*\K[^,]+" | tr -d ' ')
    if [[ -n $class_match ]]; then
        if _is_blacklisted "$class_match"; then
            echo "ERROR:blacklisted"
            return 1
        fi
    fi

    if grep -q "name = $name" "$RULES_FILE" 2>/dev/null; then
        echo "ERROR:exists"
        return 1
    fi

    local formatted_rules=""
    IFS=',' read -ra PARTS <<< "$rule_content"
    for part in "${PARTS[@]}"; do
        part=$(echo "$part" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        formatted_rules+="    $part"$'\n'
    done

    cat >>"$RULES_FILE" <<EOF
windowrule {
    name = $name
$formatted_rules}
EOF

    _apply_rules
}

_add_layerrule() {
    local name="$1"
    local rule_content="$2"

    init_rules_file

    if grep -q "name = $name" "$RULES_FILE" 2>/dev/null; then
        echo "ERROR:exists"
        return 1
    fi

    local formatted_rules=""
    IFS=',' read -ra PARTS <<< "$rule_content"
    for part in "${PARTS[@]}"; do
        part=$(echo "$part" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        formatted_rules+="    $part"$'\n'
    done

    cat >>"$RULES_FILE" <<EOF
layerrule {
    name = $name
$formatted_rules}
EOF

    _apply_rules
}

_add_anon_rule() {
    local type="$1"
    local rule_content="$2"

    init_rules_file

    if [[ $type == "window" ]]; then
        cat >>"$RULES_FILE" <<EOF
windowrule = $rule_content
EOF
    elif [[ $type == "layer" ]]; then
        cat >>"$RULES_FILE" <<EOF
layerrule = $rule_content
EOF
    fi

    _apply_rules
}

_remove_rule() {
    local name="$1"

    init_rules_file

    if ! grep -q "name = $name" "$RULES_FILE" 2>/dev/null; then
        echo "ERROR:not_found"
        return 1
    fi

    local temp_file=$(mktemp)
    local in_rule=false

    while IFS= read -r line; do
        if [[ $line =~ ^windowrule ]]; then
            in_rule=true
        elif [[ $line =~ ^layerrule ]]; then
            in_rule=true
        elif [[ $line =~ ^[[:space:]]*\}[[:space:]]*$ ]] && $in_rule; then
            in_rule=false
            continue
        elif $in_rule; then
            if [[ $line =~ name ]]; then
                continue
            fi
        fi

        if ! $in_rule; then
            echo "$line" >>"$temp_file"
        fi
    done <"$RULES_FILE"

    mv "$temp_file" "$RULES_FILE"

    _apply_rules
}

_apply_rules() {
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl reload >/dev/null 2>&1
    fi
    echo "APPLIED"
}

_get_rule_content() {
    local name="$1"
    local temp_file=$(mktemp)
    local in_rule=false

    while IFS= read -r line; do
        if [[ $line =~ ^windowrule ]]; then
            in_rule=true
        elif [[ $line =~ ^layerrule ]]; then
            in_rule=true
        elif [[ $line =~ ^[[:space:]]*\}[[:space:]]*$ ]] && $in_rule; then
            in_rule=false
        elif $in_rule; then
            echo "$line" >>"$temp_file"
        fi
    done <"$RULES_FILE"

    cat "$temp_file"
    rm -f "$temp_file"
}

case "$1" in
    "--list")
        _list_rules
        ;;
    "--add")
        _add_windowrule "$2" "$3"
        ;;
    "--add-layer")
        _add_layerrule "$2" "$3"
        ;;
    "--add-anon")
        _add_anon_rule "$2" "$3"
        ;;
    "--remove")
        _remove_rule "$2"
        ;;
    "--get")
        _get_rule_content "$2"
        ;;
    "--apply")
        _apply_rules
        ;;
    "--blacklist")
        echo "$RETRO_WINDOW_BLACKLIST"
        ;;
esac
