#!/bin/bash

source "$RETRO_DIR/lib/helpers.sh"

RULES_FILE="$RETRO_CONFIG/windowrules.lua"

mkdir -p "$(dirname "$RULES_FILE")"

init_rules_file() {
    if [[ ! -f $RULES_FILE ]]; then
        cat >"$RULES_FILE" <<'EOF'
-- This file has been generated by Retro. Do not edit manually.
-- Use retro window add / retro window remove to manage rules

EOF
    fi
}

_is_blacklisted() {
    local class="$1"
    local blacklist=$(get_var "RETRO_WINDOW_BLACKLIST")

    [[ -z $blacklist || $blacklist == "null" ]] && return 1

    IFS='|' read -ra BLACKLIST <<<"$blacklist"
    for item in "${BLACKLIST[@]}"; do
        [[ ${class,,} == "${item,,}" ]] && return 0
    done

    return 1
}

_list_rules() {
    init_rules_file

    local anon_counter=0
    local in_rule=false
    local rule_type=""
    local current_name=""

    while IFS= read -r line; do
        if [[ $line =~ ^hl\.(window_rule|layer_rule)\(\{$ ]]; then
            rule_type="${BASH_REMATCH[1]}"
            if [[ $rule_type == "window_rule" ]]; then
                rule_type="window"
            else
                rule_type="layer"
            fi
            in_rule=true
            current_name=""
        elif [[ $line =~ ^[[:space:]]*name[[:space:]]*=[[:space:]]*\"([^\"]+)\" ]]; then
            current_name="${BASH_REMATCH[1]}"
        elif [[ $line =~ ^\}\) ]]; then
            if [[ -n $current_name ]]; then
                if [[ $current_name == anon-* ]]; then
                    ((anon_counter++))
                fi
                echo "${rule_type}|${current_name}"
            fi
            in_rule=false
            current_name=""
        fi
    done <"$RULES_FILE"
}

_add_windowrule() {
    local name="$1"
    local rule_content="$2"

    init_rules_file

    if grep -q 'name = "'"$name"'"' "$RULES_FILE" 2>/dev/null; then
        echo "ERROR:exists"
        return 1
    fi

    local indented=$(echo "$rule_content" | sed 's/^/    /')

    cat >>"$RULES_FILE" <<EOF
hl.window_rule({
    name = "${name}",
${indented}
})

EOF

    _apply_rules
}

_add_layerrule() {
    local name="$1"
    local rule_content="$2"

    init_rules_file

    if grep -q 'name = "'"$name"'"' "$RULES_FILE" 2>/dev/null; then
        echo "ERROR:exists"
        return 1
    fi

    local indented=$(echo "$rule_content" | sed 's/^/    /')

    cat >>"$RULES_FILE" <<EOF
hl.layer_rule({
    name = "${name}",
${indented}
})

EOF

    _apply_rules
}

_add_anon_rule() {
    local type="$1"
    local rule_content="$2"

    init_rules_file

    local anon_num=$(grep -c "^hl\.${type}_rule" "$RULES_FILE" 2>/dev/null)
    local name="anon-$((anon_num + 1))"

    local indented=$(echo "$rule_content" | sed 's/^/    /')

    cat >>"$RULES_FILE" <<EOF
hl.${type}_rule({
    name = "${name}",
${indented}
})

EOF

    _apply_rules
}

_remove_rule() {
    local target_name="$1"

    init_rules_file

    if ! grep -q 'name = "'"$target_name"'"' "$RULES_FILE" 2>/dev/null; then
        echo "ERROR:not_found"
        return 1
    fi

    local temp_file=$(mktemp)
    local in_rule=false
    local skip_rule=false
    local current_name=""
    local pending_header=""

    while IFS= read -r line; do
        if [[ $line =~ ^hl\.(window_rule|layer_rule)\(\{$ ]]; then
            in_rule=true
            skip_rule=false
            current_name=""
            pending_header="$line"
            continue
        fi

        if $in_rule; then
            if [[ $line =~ ^[[:space:]]*name[[:space:]]*=[[:space:]]*\"([^\"]+)\" ]]; then
                current_name="${BASH_REMATCH[1]}"
                if [[ $current_name == "$target_name" ]]; then
                    skip_rule=true
                    pending_header=""
                fi
            fi

            if $skip_rule; then
                if [[ $line =~ ^\}\) ]]; then
                    in_rule=false
                    skip_rule=false
                fi
                continue
            fi

            if [[ -n $pending_header ]]; then
                echo "$pending_header" >>"$temp_file"
                pending_header=""
            fi

            if [[ $line =~ ^\}\) ]]; then
                echo "$line" >>"$temp_file"
                echo "" >>"$temp_file"
                in_rule=false
                continue
            fi
        fi

        if [[ -z $pending_header ]]; then
            echo "$line" >>"$temp_file"
        fi
    done <"$RULES_FILE"

    mv "$temp_file" "$RULES_FILE"

    _apply_rules
}

_apply_rules() {
    if command -v hyprctl >/dev/null 2>&1; then
        bash "$RETRO_DIR/modules/hyprland/files/scripts/refresh_hyprland.sh" >/dev/null 2>&1 || true
    fi
    echo "APPLIED"
}

_get_rule_content() {
    local name="$1"
    local temp_file=$(mktemp)
    local in_rule=false
    local capturing=false

    while IFS= read -r line; do
        if [[ $line =~ ^hl\.(window_rule|layer_rule)\(\{$ ]]; then
            in_rule=true
            capturing=false
        fi

        if $in_rule; then
            if [[ $line =~ ^[[:space:]]*name[[:space:]]*=[[:space:]]*\"([^\"]+)\" ]]; then
                if [[ ${BASH_REMATCH[1]} == "$name" ]]; then
                    capturing=true
                fi
            elif [[ $line =~ ^\}\) ]]; then
                in_rule=false
                capturing=false
            elif $capturing; then
                local cleaned=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//;s/,$//')
                if [[ -n $cleaned ]]; then
                    echo "$cleaned"
                fi
            fi
        fi
    done <"$RULES_FILE"
}

case "$1" in
    "--list")
        _list_rules
        ;;
    "--add")
        _add_windowrule "$2" "$3"
        ;;
    "--add-layer")
        _add_layerrule "$2" "$3"
        ;;
    "--add-anon")
        _add_anon_rule "$2" "$3"
        ;;
    "--remove")
        _remove_rule "$2"
        ;;
    "--get")
        _get_rule_content "$2"
        ;;
    "--apply")
        _apply_rules
        ;;
    "--blacklist")
        echo "$RETRO_WINDOW_BLACKLIST"
        ;;
esac
