$image = /home/vlad/.config/retro/wallpapers/retro/retrowave-gtr-wallpaper.jpg


$background = #f9f9f9

$error = #ba1a1a

$error_container = #ffdad6

$inverse_on_surface = #f1f1f1

$inverse_primary = #f8adfc

$inverse_surface = #303030

$on_background = #1b1b1b

$on_error = #ffffff

$on_error_container = #410002

$on_primary = #ffffff

$on_primary_container = #36003f

$on_primary_fixed = #36003f

$on_primary_fixed_variant = #6b2d72

$on_secondary = #ffffff

$on_secondary_container = #251626

$on_secondary_fixed = #251626

$on_secondary_fixed_variant = #534153

$on_surface = #1b1b1b

$on_surface_variant = #474747

$on_tertiary = #ffffff

$on_tertiary_container = #33110c

$on_tertiary_fixed = #33110c

$on_tertiary_fixed_variant = #673b34

$outline = #777777

$outline_variant = #c6c6c6

$primary = #85468c

$primary_container = #ffd6fd

$primary_fixed = #ffd6fd

$primary_fixed_dim = #f8adfc

$scrim = #000000

$secondary = #6c586b

$secondary_container = #f4dbf1

$secondary_fixed = #f4dbf1

$secondary_fixed_dim = #d8bfd5

$shadow = #000000

$source_color = #bf49d0

$surface = #f9f9f9

$surface_bright = #f9f9f9

$surface_container = #eeeeee

$surface_container_high = #e8e8e8

$surface_container_highest = #e2e2e2

$surface_container_low = #f3f3f3

$surface_container_lowest = #ffffff

$surface_dim = #dadada

$surface_tint = #85468c

$surface_variant = #e2e2e2

$tertiary = #82524a

$tertiary_container = #ffdad4

$tertiary_fixed = #ffdad4

$tertiary_fixed_dim = #f6b8ad

