cursor            #85468c
cursor_text_color #ffffff

foreground        #1b1b1b
background        #f9f9f9

selection_foreground #ffffff
selection_background #6c586b
url_color         #85468c

#: black
color0  #954e9f
color8  #6f3a77

#: red 
color1  #49264f
color9  #5c3063

#: green 
color2  #954d9e
color10 #954d9e

#: yellow 
color3  #231328
color11 #49264f

#: blue 
color4  #85468c
color12 #ffd6fd

#: magenta
color5  #bf49d0
color13 #231328

#: cyan 
color6  #954d9e
color14 #59295f

#: white 
color7  #474747
color15 #361d3c

# --- Tab Bar & Borders ---
active_tab_foreground   #ffffff
active_tab_background   #85468c
active_border_color     #85468c
inactive_border_color   #777777
