$image = /home/vlad/.config/retro/wallpaper_frames/car-in-neon-gas-station.mp4.png


$background = rgba(17111aff)

$error = rgba(ffece9ff)

$error_container = rgba(ffaea4ff)

$inverse_on_surface = rgba(000000ff)

$inverse_primary = rgba(7200aaff)

$inverse_surface = rgba(ebdeedff)

$on_background = rgba(ebdeedff)

$on_error = rgba(000000ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(000000ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(200034ff)

$on_secondary = rgba(000000ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(1e0821ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(ffffffff)

$on_tertiary = rgba(000000ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(260220ff)

$outline = rgba(f9ecfaff)

$outline_variant = rgba(cbbfccff)

$primary = rgba(fcebffff)

$primary_container = rgba(e3afffff)

$primary_fixed = rgba(f5d9ffff)

$primary_fixed_dim = rgba(e5b4ffff)

$scrim = rgba(000000ff)

$secondary = rgba(ffeafbff)

$secondary_container = rgba(dcb7daff)

$secondary_fixed = rgba(fdd7faff)

$secondary_fixed_dim = rgba(e0bbdeff)

$shadow = rgba(000000ff)

$source_color = rgba(a83be9ff)

$surface = rgba(17111aff)

$surface_bright = rgba(564d59ff)

$surface_container = rgba(352e38ff)

$surface_container_high = rgba(413943ff)

$surface_container_highest = rgba(4c444fff)

$surface_container_low = rgba(241d27ff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(17111aff)

$surface_tint = rgba(e5b4ffff)

$surface_variant = rgba(4c444fff)

$tertiary = rgba(ffebf4ff)

$tertiary_container = rgba(edb1d8ff)

$tertiary_fixed = rgba(ffd7efff)

$tertiary_fixed_dim = rgba(f1b4dcff)

