$image = /home/vlad/.config/retro/wallpapers/retro/retrowave-gtr-wallpaper.jpg


$background = #131313

$error = #ffb4ab

$error_container = #93000a

$inverse_on_surface = #303030

$inverse_primary = #85468c

$inverse_surface = #e2e2e2

$on_background = #e2e2e2

$on_error = #690005

$on_error_container = #ffdad6

$on_primary = #51145a

$on_primary_container = #ffd6fd

$on_primary_fixed = #36003f

$on_primary_fixed_variant = #6b2d72

$on_secondary = #3b2b3c

$on_secondary_container = #f4dbf1

$on_secondary_fixed = #251626

$on_secondary_fixed_variant = #534153

$on_surface = #e2e2e2

$on_surface_variant = #c6c6c6

$on_tertiary = #4c251f

$on_tertiary_container = #ffdad4

$on_tertiary_fixed = #33110c

$on_tertiary_fixed_variant = #673b34

$outline = #919191

$outline_variant = #474747

$primary = #f8adfc

$primary_container = #6b2d72

$primary_fixed = #ffd6fd

$primary_fixed_dim = #f8adfc

$scrim = #000000

$secondary = #d8bfd5

$secondary_container = #534153

$secondary_fixed = #f4dbf1

$secondary_fixed_dim = #d8bfd5

$shadow = #000000

$source_color = #bf49d0

$surface = #131313

$surface_bright = #393939

$surface_container = #1f1f1f

$surface_container_high = #2a2a2a

$surface_container_highest = #353535

$surface_container_low = #1b1b1b

$surface_container_lowest = #0e0e0e

$surface_dim = #131313

$surface_tint = #f8adfc

$surface_variant = #474747

$tertiary = #f6b8ad

$tertiary_container = #673b34

$tertiary_fixed = #ffdad4

$tertiary_fixed_dim = #f6b8ad

