cursor            #fcebff
cursor_text_color #000000

foreground        #ffffff
background        #17111a

selection_foreground #000000
selection_background #ffeafb
url_color         #fcebff

#: black
color0  #0f0f12
color8  #3d224c

#: red 
color1  #6b3586
color9  #542c69

#: green 
color2  #b051dd
color10 #b051dd

#: yellow 
color3  #9948c0
color11 #6b3586

#: blue 
color4  #fcebff
color12 #f5d9ff

#: magenta
color5  #a83be9
color13 #9948c0

#: cyan 
color6  #b051dd
color14 #542374

#: white 
color7  #ffffff
color15 #823fa3

# --- Tab Bar & Borders ---
active_tab_foreground   #000000
active_tab_background   #fcebff
active_border_color     #fcebff
inactive_border_color   #f9ecfa
