-- This file has been generated by Retro. Do not edit manually.

return {
    retro_opacity = 0.9,
    retro_inactive_opacity = 0.8,
    retro_border_size = 2,
    retro_rounding = 25,
    retro_rounding_power = 2,
    retro_gap_in = 5,
    retro_gap_out = 20,
    retro_shadow = true,
    retro_shadow_range = 4,
    retro_shadow_render_power = 3,
    retro_blur = true,
    retro_blur_size = 3,
    retro_blur_passes = 3,
    retro_blur_vibrancy = 0.1696,
}
