name: ISO Build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build ISO
        env:
          RETRO_DIR: ${{ github.workspace }}
        run: |
          chmod +x ./iso/build.sh
          ./iso/build.sh -y

      - name: Find ISO
        id: iso
        run: |
          ISO_FILE=$(ls iso/out/*.iso | head -1)
          echo "filename=$(basename $ISO_FILE)" >> $GITHUB_OUTPUT

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: retrolinux-iso
          path: iso/out/*.iso
          retention-days: 5